package com.samuelchowi.mhwlibrary.ui.theme

import androidx.compose.ui.graphics.Color

// Light Colors
val md_theme_primary_light = Color(0xFFDCE9F5)
val md_theme_onPrimary_light = Color(0xFF011A27)
val md_theme_primaryContainer_light = Color(0xFFC6D9E9)
val md_theme_onPrimaryContainer_light = Color(0xFF063442)
val md_theme_secondary_light = Color(0xFF4F606E)
val md_theme_onSecondary_light = Color(0xFFFFFFFF)
val md_theme_secondaryContainer_light = Color(0xFFDCE9F5)
val md_theme_onSecondaryContainer_light = Color(0xFF0B1D29)
val md_theme_tertiary_light = Color(0xFFC2B3EB)
val md_theme_onTertiary_light = Color(0xFFFFFFFF)
val md_theme_tertiaryContainer_light = Color(0xFFDDD8E7)
val md_theme_onTertiaryContainer_light = Color(0xFF1F1635)
val md_theme_error_light = Color(0xFFBA1A1A)
val md_theme_onError_light = Color(0xFFFFFFFF)
val md_theme_background_light = Color(0xFFEAEFF7)
val md_theme_onBackground_light = Color(0xFF181C20)
val md_theme_surface_light = Color(0xFFF6F9FE)
val md_theme_onSurface_light = Color(0xFF181C20)
val md_theme_outline_light = Color(0xFF71787E)
val md_theme_SurfaceVariant_light = Color(0xFFDAE4E9)
val md_theme_onSurfaceVariant_light = Color(0xFF0D1614)

// Dark Colors
val md_theme_primary_dark = Color(0xFF384956)
val md_theme_onPrimary_dark = Color(0xFFAEC3D5)
val md_theme_primaryContainer_dark = Color(0xFF163E4E)
val md_theme_onPrimaryContainer_dark = Color(0xFFDAE5EE)
val md_theme_secondary_dark = Color(0xFFB7C9D8)
val md_theme_onSecondary_dark = Color(0xFF21323F)
val md_theme_secondaryContainer_dark = Color(0xFF384956)
val md_theme_onSecondaryContainer_dark = Color(0xFFD3E5F5)
val md_theme_tertiary_dark = Color(0xFF202844)
val md_theme_onTertiary_dark = Color(0xFF9C91B9)
val md_theme_tertiaryContainer_dark = Color(0xFF4B4163)
val md_theme_onTertiaryContainer_dark = Color(0xFFE9DDFF)
val md_theme_error_dark = Color(0xFFFFB4AB)
val md_theme_onError_dark = Color(0xFF690005)
val md_theme_background_dark = Color(0xFF212A31)
val md_theme_onBackground_dark = Color(0xFFDFE3E8)
val md_theme_surface_dark = Color(0xFF101417)
val md_theme_onSurface_dark = Color(0xFFDFE3E8)
val md_theme_outline_dark = Color(0xFF8B9198)
val md_theme_SurfaceVariant_dark = Color(0xFF365268)
val md_theme_onSurfaceVariant_dark = Color(0xFFF5F8F8)